### ISSUE TITLE
Action API action=logout will require a CSRF token

### ISSUE THREAD

**Issue by Jayprakash-SE** [wikimedia/mediawiki-api-demos#118]
With the merge of Icb674095,[1] use of API action=logout will require a
CSRF token. This was considered a security issue, so the usual deprecation
process was not followed. See T25227[2] for details.

[1] https://gerrit.wikimedia.org/r/c/mediawiki/core/+/504565
[2] https://phabricator.wikimedia.org/T25227

See full context at https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2019-April/000145.html

**Comment by Jayprakash-SE** [comment]
This change will be deployed on Wikimedia Sites with 1.34.0-wmf.3 version, Which is scheduled for Thursday, 02 May 2019. I am holding this until.

**Comment by srish** [comment]
This issue is about modifying [logout.py](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/blob/master/python/logout.py) and corresponding changes to [API:Logout](https://www.mediawiki.org/wiki/API:Logout) on MediaWiki.org one the new changes to the API module are deployed.

**Comment by srish** [comment]
Addressed here https://github.com/wikimedia/mediawiki-api-demos/pull/120.
