### ISSUE TITLE
Rewrite API:Deletedrevs

### ISSUE THREAD

**Issue by Jayprakash-SE** [wikimedia/mediawiki-api-demos#143]
Deletedrevs should remove from the modules.json because to make such request we have to give the login user session. So we have to write this module again.

**Comment by srish** [comment]
@Jayprakash-SE But, is the module itself not deprecated: https://www.mediawiki.org/w/index.php?title=API:Deletedrevs and suppose to work only with MediaWiki v <1.25? If so, the information I believe on the module page is right. If not, then we would need to make changes to it.

**Comment by Jayprakash-SE** [comment]
> @Jayprakash-SE But, is the module itself not deprecated: https://www.mediawiki.org/w/index.php?title=API:Deletedrevs and suppose to work only with MediaWiki v <1.25? If so, the information I believe on the module page is right. If not, then we would need to make changes to it.

Ok Ji, I need to check the MediaWiki Settings file. so that we can confirm that for MediaWiki v <1.25, non-login users can see the revisions. But in the current versions, only sysop/suppress is able to view the detected revisions.

**Comment by Jayprakash-SE** [comment]
@srish Ji, As per the [MediaWiki 1.14.1](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/1.14.1/includes/api/ApiQueryDeletedrevs.php#46) users have to deletedhistory rights to view such revisions and per [MediaWiki 1.14's DefaultSettings.php](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/1.14.1/includes/DefaultSettings.php#1208) the only sysop has these rights. So now we have to write this module to ensure the query should be made by an active login user session.

**Comment by srish** [comment]
(if you have some time left from GSoC project it would be nice to receive improvement on the existing code snippet)
