### ISSUE TITLE
Write sample code in MediaWiki JS to get a user's watchlist feed

### ISSUE THREAD

**Issue by srish** [wikimedia/mediawiki-api-demos#169]
To be documented here: https://www.mediawiki.org/wiki/API:Watchlist_feed

**Comment by monique1087** [comment]
Hello! My name is Mnique and I want to contribute. How could I do that?

**Comment by brendajerop** [comment]
@monique1087 Sorry for the late reply :/ Would you like to contribute as part of Outreachy?

**Comment by NamanZelawat** [comment]
@srish Hello! I am Naman Zelawat and I would like to contribute, can you explain in more detail what work should be done.

**Comment by srish** [comment]
Closing this task as it was associated with an internship project that is now complete.
