### ISSUE TITLE
Write sample code to demonstrate importing a page from another wiki via xml dump

### ISSUE THREAD

**Issue by srish** [wikimedia/mediawiki-api-demos#171]
Currently, we are missing the PHP and MediaWikiJS version here: https://www.mediawiki.org/wiki/API:Import/Sample_code_2

**Comment by 75pollet** [comment]
can i work on this?

**Comment by brendajerop** [comment]
@75pollet Feel free to create a pull request for this issue :)

**Comment by srish** [comment]
Closing this task as it was associated with an internship project that is now complete.
