### ISSUE TITLE
A tool to search Wiki articles by your location

### ISSUE THREAD

**Issue by janko216** [wikimedia/mediawiki-api-demos#175]
* [Wikiaround](https://slavneobrazy.cz/wikiaround/):
Uses geo search for wiki articles, user's location and Google maps to display. Based on MediaWiki Action API's [Geosearch](https://www.mediawiki.org/wiki/API:Geosearch) module.

**Comment by NamanZelawat** [comment]
@janko216 I would like to work. Can you explain things in more detail?

**Comment by brendajerop** [comment]
@janko216 Nice app! Does it fit the criteria mentioned in [contributing.md](https://github.com/wikimedia/mediawiki-api-demos/blob/master/gallery/contributing.md)?

**Comment by janko216** [comment]
HI, I'm not sure, but I guess yes  :-)

Petr

Petr Pakosta
petr@slavneobrazy.cz
telefon 608 969 108


pá 15. 5. 2020 v 6:19 odesílatel Jerop Brenda <notifications@github.com>
napsal:

**Comment by brendajerop** [comment]
@janko216 Great! Feel free to open a pull request for it. You can find instructions on how to add an app to the gallery [here](https://github.com/wikimedia/mediawiki-api-demos/blob/master/gallery/contributing.md) in the sub-section `Submitting your app`. I would do it but I cannot find information such as the link to the source code.

**Comment by srish** [comment]
I'm closing this issue as we already have a similar demo app in this repo. See https://github.com/wikimedia/mediawiki-api-demos/tree/master/apps/nearby-places-viewer.
