### ISSUE TITLE
Link to mediawikijs code samples from mediawikijs/README.md

### ISSUE THREAD

**Issue by brendajerop** [wikimedia/mediawiki-api-demos#188]
[mediawikijs/README.md](https://github.com/wikimedia/mediawiki-api-demos/blob/master/mediawikijs/README.md) should contain links to all the [mediawikijs](https://github.com/wikimedia/mediawiki-api-demos/tree/master/mediawikijs) code samples available.

**Comment by zainababubakar** [comment]
@brendajerop, can i work on this issue ?

**Comment by brendajerop** [comment]
@zainababubakar Sure...I've assigned it to you.

**Comment by Rubaaw** [comment]
Hi. Can i work on this issue, or it is completely taken ?

**Comment by zainababubakar** [comment]
> Hi. Can i work on this issue, or it is completely taken ?

Yes it's completely taken, I'm working on it

**Comment by Rubaaw** [comment]
> 
> 
> > Hi. Can i work on this issue, or it is completely taken ?
> 
> Yes it's completely taken, I'm working on it

Thanks and Good luck
