### ISSUE TITLE
Implement "API:Get the contents of a page" in Python

### ISSUE THREAD

**Issue by ZihanChen1995** [wikimedia/mediawiki-api-demos#222]
Hi! I'm learning to use Wiki API to get the public information of users. I found the script, ["get_users.py"](https://github.com/wikimedia/mediawiki-api-demos/blob/master/python/get_users.py), in MediaWiki-API-demos that can help us get general information, like edit count or email address. However, the personal description on the user page can not be fetched in this way. 

(An example is shown below. I want to get the text information like "I'm not usually active on English Wikipedia. Please refer ...")

<img width="1233" alt="Screen Shot 2020-06-05 at 5 49 41 PM" src="https://user-images.githubusercontent.com/36064256/83925377-0370bc00-a755-11ea-89fc-9a032b7ae220.png">

I found that ["API: Get the contents of a page" ](https://www.mediawiki.org/wiki/API:Get_the_contents_of_a_page) offers an option to achieve that. Because I know nothing about PHP, may I ask is there any way we can get these text contents using the API in Python? 

Thank you a lot for your time in advance!

**Comment by Jayprakash-SE** [comment]
https://github.com/wikimedia/mediawiki-api-demos/blob/master/python/get_pages_revisions.py will help you to get the text.

**Comment by Jayprakash-SE** [comment]
Example:-
```
import requests

S = requests.Session()

URL = "https://en.wikipedia.org/w/api.php"

PARAMS = {
    "action": "query",
    "prop": "revisions",
    "titles": "User:Catrope",
    "rvprop": "timestamp|user|comment|content",
    "rvslots": "main",
    "formatversion": "2",
    "format": "json"
}

R = S.get(url=URL, params=PARAMS)
DATA = R.json()

PAGES = DATA["query"]["pages"]

for page in PAGES:
    print(page["revisions"][0]["slots"]["main"]["content"])
```

**Comment by ZihanChen1995** [comment]
Hi Jayprakash, thank you a lot for your quick and helpful reply. It works now! May I have two more question? When you mentioned `"titles": "User:Catrope"`, it refers to the whole page under this title, right? 

<img width="370" alt="Screen Shot 2020-06-05 at 6 17 53 PM" src="https://user-images.githubusercontent.com/36064256/83926826-feae0700-a758-11ea-8634-2ec2ba1f9f13.png">

1. Since there are two options here: User page and talk, how could you point out: Well we are working on the user page at this moment? Is this achieved by your last line of code? `page["revisions"][0]["slots"]["main"]["content"]` While `Page[0]` means the User page and [1] means the talk?

2. If I want to search for a list of users, can I just add `"titles": "User:A"|"User:B"|"User:C"` as in other scripts? Or we need to search them one by one?


Thank you again for your help!

**Comment by Jayprakash-SE** [comment]
> 1.
> Ans:- No, `page["revisions"][0]` shows that we need latest revision (`[0]`) from list of revisions. I guess you just need the latest revision of the page. if you want the text of Talk page then you have to give talk page name in `titles`. like `"titles": "User:Catrope|User_talk:Catrope"`

>2. 
>For list of users, you should use https://github.com/wikimedia/mediawiki-api-demos/blob/master/python/get_allusers.py, Just give prefix and it will return the users list. Use `aulimit` parameter to get more users.

**Comment by ZihanChen1995** [comment]
Thank you again, Jayprakash. I just tried your answer of question 1, it works perfectly now. 

And for question 2, I checked the script you mentioned. It works like a "generator", right? As it returns all the users start with the exact "prefix" you defined. However, my situation is that: Now I have an existing list of users, and I want to search them one by one.
(The data looks like in this way)

<img width="329" alt="Screen Shot 2020-06-05 at 6 50 53 PM" src="https://user-images.githubusercontent.com/36064256/83928371-90b80e80-a75d-11ea-9d01-04fffbbdb00c.png">

Do you know there is any way we can execute them at once? (Or if there is no other way, looping them one by one then inputting them into the code you mentioned are still quite fast. Thank you for that again!)

**Comment by ZihanChen1995** [comment]
Hi Jayprakash. I think about it for a while. Actually even I can add more user names into the `PARAMS`, every time I ask for the personal info from the API, it just executes the query request for each user at each time. Hence there should be no efficiency difference between outside loop or inside one. 

Thank you for your patience and information. That's all I need. Have a great week!
