### ISSUE TITLE
Wrong github url for user-contributions-app on the gallery

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/mediawiki-api-demos#223]
**Problem**
On the apps gallery, clicking on the "view on github" button of the User Contributions app sends you instead to [article-ideas-generator](https://github.com/wikimedia/mediawiki-api-demos/tree/master/apps/article-ideas-generator) app.

**Expected behavior**
It is supposed to open up a tab to [user-contributions-app](https://github.com/wikimedia/mediawiki-api-demos/tree/master/apps/user-contributions-feed)

**Comment by Jayprakash-SE** [comment]
Thank you for your contribution.
