### ISSUE TITLE
SSL connection issue

### ISSUE THREAD

**Issue by naramoksu** [wikimedia/mediawiki-api-demos#225]
Hi, 

I had installed your python code and found it worked on wikipedia. I tried to connect my private wiki and found ssl issues. 

After lots of try and error, suddenly  I found the code succeed to make new wiki document. But it is not repeated. 

Would you kindly advice me what to check to avoid ssl iissues? 

Thanks in advance.

**Comment by Jayprakash-SE** [comment]
Did you try your wiki URL with `http://` instead of `https://`?

**Comment by naramoksu** [comment]
Thanks for your suggestion. I tried but not worked. 

The issue is "certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)"
I'm trying to find out the reason and way to fix. If you have any advice, let me know. 

Have a good day.

**Comment by ervand7** [comment]
Thank you very much for you work)
