### ISSUE TITLE
Nearby places viewer. 500 Internal Server error

### ISSUE THREAD

**Issue by harry-wood** [wikimedia/mediawiki-api-demos#229]
I tried playing with this thing https://nearby-places-viewer.toolforge.org/nearby-places-viewer/  (found via https://www.mediawiki.org/wiki/API:Nearby_places_viewer ) 

But it's posting to the same URL and getting back a 500 Internal Server error

I don't know if it's an issue with in the code, or just something need fixing on the server. What does the error log say?

**Comment by srish** [comment]
@harry-wood thanks for filing this issue! Sorry it took so long to address it. It is not the most actively maintained repository.I just reinstalled a bunch of modules on the server and it worked! Closing it for now.
