### ISSUE TITLE
"Account Creator" down and source 404

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/mediawiki-api-demos#230]
1. https://developer.wikimedia.org/ first link: https://developer.wikimedia.org/use-content/ first link: https://developer.wikimedia.org/use-content/featured-apps/ first link: https://apps-gallery.toolforge.org/
2. "Account Creator"
3. "Try it out": <https://tools.wmflabs.org/account-creator/>
   * 502 Bad Gateway (after a redirect to <https://account-creator.toolforge.org/>)
4. "View on GitHub": <https://github.com/wikimedia/mediawiki-api-demos/tree/master/apps/create-account-with-captcha>
   * 404 Not Found

Looks like the latter is now at <https://github.com/wikimedia/mediawiki-api-demos/tree/master/apps/account-creator>.

**Comment by srish** [comment]
@Krinkle Thanks for filing this! The issue has been resolved now.
