### ISSUE TITLE
Wikimedia Image upload via API - help needed for mapcomplete

### ISSUE THREAD

**Issue by hermann-san** [wikimedia/mediawiki-api-demos#232]
Hi,
the [Mapcomplete](https://github.com/pietervdvn/MapComplete) dev Peter is asking for help with uploading images to Wikimedia Commons via the Wikimedia API.
Mapcomplete is an awesome tool to build maps with OSM data. 
If someone could help Peter (or you know someone who potentially could) , it would be great
https://github.com/pietervdvn/MapComplete/issues/99

Thanks a lot.

**Comment by aklapper** [comment]
@hermann-san Hi, this issue does not seem to be about the MediaWiki API Demos so I'm closing it. Please see https://developer.wikimedia.org/ for general information where to bring up questions - thanks a lot!
